/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package es.jclorenzo.exercises.springboot.currency.client;

import java.util.List;

import es.jclorenzo.exercises.springboot.currency.model.Currency;

/**
 * The Interface CurrencyClient.
 */
public interface CurrencyRemoteClient {

	/**
	 * Gets the currencies.
	 *
	 * @return the currencies
	 */
	List<Currency> getCurrencies();

	/**
	 * Gets the currency by code.
	 *
	 * @param currencyCode the currency code
	 * @return the currency by code
	 */
	Currency getCurrencyByCode(String currencyCode);

}
